services:
  # Nama layanan Anda (misalnya: web-app, backend, database)
  my_app:
    # Perintah ini memberitahu Docker Compose untuk
    # membangun image menggunakan Dockerfile yang ada di
    # konteks (path) yang ditentukan.
    build:
      # Titik (`.`) menunjukkan direktori konteks build adalah
      # direktori saat ini, di mana docker-compose.yml berada.
      context: .

    # Opsional: Tentukan port mapping (HOST_PORT:CONTAINER_PORT)
    ports:
      - "8000:8020"

    env_file:
      - .env

    volumes:
      - ./.env:/var/www/html/.env:ro
    restart: unless-stopped
